-- Migration 026: Add status column to machines table
--
-- The MachineStatus enum (online/offline/unknown) is distinct from the
-- enabled boolean. A machine can be enabled but currently offline.
-- Translated from DuckDB to SQLite-compatible SQL (bd-h6y)
--
-- NOTE: migration 002_machine_registry.sql already adds this column in the
-- translated SQLite chain, so keeping the later ALTER would fail with
-- "duplicate column name: status". This migration is therefore a deliberate
-- no-op after translation.
